name: intro_slider
description: Flutter Intro Slider is a flutter plugin that helps you make a cool intro for your app
homepage: https://github.com/duytq94/flutter-intro-slider
version: 2.3.3

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^0.19.0
  font_awesome_flutter: ^8.10.0
environment:
  sdk: ">=2.1.0 <3.0.0"
  flutter: ">=1.12.0 <2.0.0"